---
version: 2.0.0
slug: duckdns
name: Duck DNS
description: >-
  Free Dynamic DNS (DynDNS or DDNS) service with Let's Encrypt and ZeroSSL support
url: https://github.com/lildude/homeassistant-addons/tree/master/duckdns
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
map:
  - ssl:rw
options:
  domain: null
  token: null
  aliases: []
  provider: letsencrypt
  accept_terms: false
  email: ""
schema:
  domain: match(.+\.duckdns\.org)
  token: str
  aliases:
    - str
  provider: list(letsencrypt|zerossl|letsencrypt-test)
  accept_terms: bool
  email: str
  algo: list(rsa|prime256v1|secp384r1)?
  certfile: str?
  keyfile: str?
  cleanup: bool?
  seconds: int?
  ipv4: str?
  ipv6: str?
startup: services
