---
name: HA OS SSH port 22222 Configurator
version: 0.9.2
slug: haos_ssh_configurator_addon
description: >-
  This enables the SSH on port 22222. Only for Home Assistant OS.
url: https://github.com/lildude/homeassistant-addons/tree/master/HAOS_Enable_SSH
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: once
boot: manual
apparmor: true
init: false
stage: experimental
privileged:
- SYS_ADMIN
full_access: false
devices:
  - /dev/sda1
  - /dev/vda1
  - /dev/sdb1
  - /dev/mmcblk0p1
  - /dev/mmcblk1p1
  - /dev/nvme0n1p1
options:
  ssh_keys: null
  debug: false
schema:
  ssh_keys:
  - str
  debug: bool?